### ISSUE TITLE
Return the plots 

### ISSUE THREAD

**Issue by DaoFof** [lucazav/binclass-tools#1]
I would like to have the plots returned when I call the plot functions 

`def curve_PR_plot(true_y, predicted_proba, beta = 1, title = "Precision Recall Curve", show_display_modebar = True):
....
return area_under_pr_curve, full_fig`

`area_under_PR, plot = bc.curve_PR_plot(true_y=y_true,
                                     predicted_proba=proba,
                                     beta=1.5)`

**Comment by lucazav** [comment]
@DaoFof we're working on this. We'll add this feature in the next release

**Comment by GretaVilla** [comment]
@DaoFof with the new release, version 1.0.0, every graphical function now returns the figure objects as the first outputs
